# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dev_mesg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_name', models.CharField(max_length=200, null=True, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('dev_mac', models.CharField(max_length=32, null=True, verbose_name='\u8bbe\u5907MAC\u5730\u5740')),
                ('dev_last_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6700\u540e\u4e00\u6b21\u5728\u7ebf\u65f6\u95f4')),
            ],
        ),
    ]
